pull_request_rules:
  - name: Auto-merge for dependency bump pull requests
    conditions:
      - or:
        - author=dependabot[bot]
        - author=github-actions[bot]
      - label=flake update

      - check-success=Build - bolek.pve
      - check-success=Build - lolek.pve
      - check-success=Build - dziad
      - check-success=Build - ldlat
      - check-success=Build - ola.hetzner
      - check-success=Build - tolek.oracle
    actions:
      merge:
        method: squash
      delete_head_branch:
