keys:
  # Users
  - &users:
    - &lukasz 35655963B7835180125FE55DD7BCC570927C355B
  # Hosts
  - &hosts:
    - &dziad age12rpy3yed80elgpeuvwcr67s7zljuut9sg8ya2jqycpk5wwlvrv3qd99ngm
    - &ldlat age1xhv0vxwgn0fzup499sc0dae6az6la923w2vjlx698zld9dgrmpaskmnksr
    - &bolek age1gn9jn003lasz9spqfkhvgkzfhhnqth3anj652lmppz8ljhp23uks97tacc
    - &lolek age1we0m4g25wp59jgn3nw5sn4lhtgkesp35r777ry7rn4zr4s038ufq2s2kyp
    - &tola age1lwsmxcqngugcx3rrgekw8leytq2q2zjwjnnp7f8h2q338yhkqeqs7e05wt
    - &olek age1z58dyxqayvre9zanktn9gtn2p704cas874vjqd97zu5juuv975gq6jfkq2
    - &tolek age10w0y5xpwanuwmgtenvtn8lmdj4dk2ql2z93r8s48jpjxpejtkcpspy2gfd
    - &ola age16wd54jwn3q49yzwuq5c85c925qxzvtddn6l443rq3g7ylh8xvfwq2thh9c
    - &k3sserver1 age1n20tlcsr0nnawwzl7yj2tm400yen73unjwmnth65yj05dtvhevwq6t3quv
    - &k3sagent1 age13ffzsmk32srsj54j0rygz0xtm035krjjawxvg0qftg2md0nqwv2q50s0q6
creation_rules:
  - path_regex: common/secrets.ya?ml$
    key_groups:
    - age:
      - *dziad
      - *ldlat
      - *bolek
      - *lolek
      - *tola
      - *olek
      - *tolek
      - *ola
      - *k3sserver1
      - *k3sagent1
      pgp:
      - *lukasz
  - path_regex: hosts/dziad/secrets.ya?ml$
    key_groups:
    - age:
      - *dziad
      pgp:
      - *lukasz
  - path_regex: hosts/ldlat/secrets.ya?ml$
    key_groups:
    - age:
      - *ldlat
      pgp:
      - *lukasz
  - path_regex: hosts/bolek.pve/secrets.ya?ml$
    key_groups:
    - age:
      - *bolek
      pgp:
      - *lukasz
  - path_regex: hosts/lolek.pve/secrets.ya?ml$
    key_groups:
    - age:
      - *lolek
      pgp:
      - *lukasz
  - path_regex: hosts/tolek.oracle/secrets.ya?ml$
    key_groups:
    - age:
      - *tolek
      pgp:
      - *lukasz
  - path_regex: hosts/ola.hetzner/secrets.ya?ml$
    key_groups:
    - age:
      - *ola
      pgp:
      - *lukasz
