keys:
  # Users
  - &users:
    - &lukasz 35655963B7835180125FE55DD7BCC570927C355B
  # Hosts
  - &hosts:
    - &dziad age12rpy3yed80elgpeuvwcr67s7zljuut9sg8ya2jqycpk5wwlvrv3qd99ngm
    - &ldlat age1xhv0vxwgn0fzup499sc0dae6az6la923w2vjlx698zld9dgrmpaskmnksr
    - &bolek age1gn9jn003lasz9spqfkhvgkzfhhnqth3anj652lmppz8ljhp23uks97tacc
    - &lolek age1we0m4g25wp59jgn3nw5sn4lhtgkesp35r777ry7rn4zr4s038ufq2s2kyp
    - &tola age18gd7utkuzgc0j0mta0llmseqch84l64f4s2gemlkkj7ts477ddvshdnfsw
    - &olek age1cqgdkpdadv8gfvy2xcyt4s8jys4q2q43g725tsx6k07v473fluys9kljy0
    - &tolek age10w0y5xpwanuwmgtenvtn8lmdj4dk2ql2z93r8s48jpjxpejtkcpspy2gfd
    - &ola age16wd54jwn3q49yzwuq5c85c925qxzvtddn6l443rq3g7ylh8xvfwq2thh9c
    - &sandbox age1qjcte6n07hqs5u3fntvnrrg8cdlxyap0cqad52pdxu85q0te5uaq4uk5yp
creation_rules:
  - path_regex: common/secrets.ya?ml$
    key_groups:
    - age:
      - *dziad
      - *ldlat
      - *bolek
      - *lolek
      - *tola
      - *olek
      - *tolek
      - *ola
      - *sandbox
      pgp:
      - *lukasz
  - path_regex: hosts/dziad/secrets.ya?ml$
    key_groups:
    - age:
      - *dziad
      pgp:
      - *lukasz
  - path_regex: hosts/ldlat/secrets.ya?ml$
    key_groups:
    - age:
      - *ldlat
      pgp:
      - *lukasz
  - path_regex: hosts/bolek.pve/secrets.ya?ml$
    key_groups:
    - age:
      - *bolek
      pgp:
      - *lukasz
  - path_regex: hosts/lolek.pve/secrets.ya?ml$
    key_groups:
    - age:
      - *lolek
      pgp:
      - *lukasz
  - path_regex: hosts/sandbox.pve/secrets.ya?ml$
    key_groups:
    - age:
      - *sandbox
      pgp:
      - *lukasz
  - path_regex: hosts/tolek.oracle/secrets.ya?ml$
    key_groups:
      - age:
          - *tolek
        pgp:
          - *lukasz
  - path_regex: hosts/tola.pve/secrets.ya?ml$
    key_groups:
    - age:
      - *tola
      pgp:
      - *lukasz
  - path_regex: hosts/ola.hetzner/secrets.ya?ml$
    key_groups:
    - age:
      - *ola
      pgp:
      - *lukasz
