# 20230123_082528; This was generated by ‘/run/current-system/sw/bin/setup-nixos-native-encrypted-zfs-boot’
## uefi single: OK (afterwards Also boots in bios-mode)
## bios single: Ok (afterwards Doesn't show in uefi-mode)
## uefi mirror: ok, but won't boot if one is missing? why? fix?
## bios mirror: OK
{ ... }:
{
  # Use the GRUB 2 boot loader.
  boot.loader = {
    efi = {
      canTouchEfiVariables = true;
      efiSysMountPoint = "/boot"; # use the same mount point here.
    };
    grub = {
      enable = true;
      version = 2;
      # efiInstallAsRemovable = true;
      # Prevents boot error: external pointer tables not supported. This happens when: ZFS root file system + The number of hardlinks in the nix store gets very high.
      copyKernels = true;
      zfsSupport = true;
      efiSupport = true;
      mirroredBoots = [
        { devices = [ "/dev/disk/by-id/ata-CT480BX500SSD1_1943E3D06372" ]; path = "/boot1"; }
        { devices = [ "/dev/disk/by-id/ata-CT480BX500SSD1_1847E16438D3" ]; path = "/boot2"; }
      ];
    };
  };
  boot.zfs.requestEncryptionCredentials = false;
  fileSystems."/" = {
    neededForBoot = true;
  };
  fileSystems."/nix" = {
    neededForBoot = true;
  };
  fileSystems."/persist" = {
    neededForBoot = true;
  };
  fileSystems."/ssync" = {
    neededForBoot = true;
  };
  fileSystems."/cache" = {
    neededForBoot = true;
  };
  fileSystems."/boot1" = {
    # nofail: Makes it possible to boot with only 1 mirror present.
    options = [ "nofail" ]; # https://discourse.nixos.org/t/nixos-on-mirrored-ssd-boot-swap-native-encrypted-zfs/9215/6
  };
  fileSystems."/boot2" = {
    # nofail: Makes it possible to boot with only 1 mirror present.
    options = [ "nofail" ]; # https://discourse.nixos.org/t/nixos-on-mirrored-ssd-boot-swap-native-encrypted-zfs/9215/6
  };
  networking.hostId = "a9427892"; # The primary use case is to ensure when using ZFS that a pool isn't imported accidentally on a wrong machine.
}
