# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nvim-session-manager = {
    pname = "nvim-session-manager";
    version = "4883372b1ef2bdcf4cbdac44c98d68c216914462";
    src = fetchgit {
      url = "https://github.com/Shatur/neovim-session-manager";
      rev = "4883372b1ef2bdcf4cbdac44c98d68c216914462";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-04GL+0JdtD2hEOSrRJUh3Wdpoy2igjHt95Nf3WioFU4=";
    };
    date = "2023-07-22";
  };
}
