name: "build"

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-$${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.machine.runner }}
    strategy:
      fail-fast: false
      matrix:
        machine:
          - host: bolek.pve
            platform: x86-64-linux
            runner: ubuntu-latest
            target-branch: release-bolek_pve
          - host: lolek.pve
            platform: x86-64-linux
            runner: ubuntu-latest
            target-branch: release-lolek_pve
          - host: tola.pve
            platform: x86-64-linux
            runner: ubuntu-latest
            target-branch: release-tola_pve
          - host: dziad
            platform: x86-64-linux
            runner: nixos
            target-branch: release-dziad
          - host: ldlat
            platform: x86-64-linux
            runner: nixos
            target-branch: release-ldlat
          - host: ola.hetzner
            platform: x86-64-linux
            runner: ubuntu-latest
            target-branch: release-ola_hetzner
          - host: tolek.oracle
            platform: aarch64-linux
            runner: ubuntu-latest
            target-branch: release-tolek_oracle
    name: Build - ${{ matrix.machine.host }}
    steps:
      - uses: actions/checkout@v4

      # We only run this if we are building an aarch64-linux system
      - if: matrix.machine.platform == 'aarch64-linux'
        uses: docker/setup-qemu-action@v3

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - run: tailscale ping attic.panther-crocodile.ts.net

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            fallback = true
            http-connections = 128
            max-substitution-jobs = 128
            extra-platforms = aarch64-linux
            substituters = https://hyprland.cachix.org?priority=43 https://nix-community.cachix.org?priority=41 https://cosmic.cachix.org?priority=42 https://attic.dechnik.net/system?priority=44 https://cache.nixos.org/
            trusted-public-keys = hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= system:5mtbpEmaoC7RVnZJz/KZU2Of2QXQTMBriCJjt3SK9Iw= cosmic.cachix.org-1:Dya9IyXD4xdBehWjrkPv6rtxpmMdRel02smYzA85dPE= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build and push system
        run: |
          nix run github:zhaofengli/attic#default login lukasz http://attic.panther-crocodile.ts.net ${{ secrets.ATTIC_TOKEN }}
          nix run github:zhaofengli/attic#default watch-store system &
          nix build '.#nixosConfigurations."${{ matrix.machine.host }}".config.system.build.toplevel'
          nix run github:zhaofengli/attic#default push system result -j 2 || true

      - name: Configure git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Push to target branch
        if: github.ref == 'refs/heads/master' && success()
        uses: ad-m/github-push-action@v0.8.0
        with:
          force: true
          push_to: ${{ matrix.machine.target-branch }}
